#!/bin/sh
#
# /Library/StartupItems/CRISPRdirect/CRISPRdirect
#
# A startup script of CRISPRdirect jellyfish server for Mac OS X.

. /etc/rc.common

JELFISH="/opt/CRISPRdirect/jellyfishd.pl"
HASHDIR="/genome/jellyhash"
LOGDIR="/genome/jellylog"

StartService ()
{
	ConsoleMessage "Starting CRISPRdirect jellyfish server"

	sudo -u nobody $JELFISH -p 48001 -k 23 -hash $HASHDIR/hg38/hg38_23nt.jf >> $LOGDIR/hg38_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47001 -k 15 -hash $HASHDIR/hg38/hg38_15nt.jf >> $LOGDIR/hg38_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46001 -k 11 -hash $HASHDIR/hg38/hg38_11nt.jf >> $LOGDIR/hg38_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48002 -k 23 -hash $HASHDIR/hg19/hg19_23nt.jf >> $LOGDIR/hg19_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47002 -k 15 -hash $HASHDIR/hg19/hg19_15nt.jf >> $LOGDIR/hg19_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46002 -k 11 -hash $HASHDIR/hg19/hg19_11nt.jf >> $LOGDIR/hg19_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48003 -k 23 -hash $HASHDIR/hg18/hg18_23nt.jf >> $LOGDIR/hg18_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47003 -k 15 -hash $HASHDIR/hg18/hg18_15nt.jf >> $LOGDIR/hg18_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46003 -k 11 -hash $HASHDIR/hg18/hg18_11nt.jf >> $LOGDIR/hg18_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48004 -k 23 -hash $HASHDIR/mm10/mm10_23nt.jf >> $LOGDIR/mm10_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47004 -k 15 -hash $HASHDIR/mm10/mm10_15nt.jf >> $LOGDIR/mm10_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46004 -k 11 -hash $HASHDIR/mm10/mm10_11nt.jf >> $LOGDIR/mm10_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48005 -k 23 -hash $HASHDIR/mm9/mm9_23nt.jf >> $LOGDIR/mm9_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47005 -k 15 -hash $HASHDIR/mm9/mm9_15nt.jf >> $LOGDIR/mm9_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46005 -k 11 -hash $HASHDIR/mm9/mm9_11nt.jf >> $LOGDIR/mm9_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48006 -k 23 -hash $HASHDIR/rn6/rn6_23nt.jf >> $LOGDIR/rn6_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47006 -k 15 -hash $HASHDIR/rn6/rn6_15nt.jf >> $LOGDIR/rn6_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46006 -k 11 -hash $HASHDIR/rn6/rn6_11nt.jf >> $LOGDIR/rn6_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48007 -k 23 -hash $HASHDIR/rn5/rn5_23nt.jf >> $LOGDIR/rn5_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47007 -k 15 -hash $HASHDIR/rn5/rn5_15nt.jf >> $LOGDIR/rn5_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46007 -k 11 -hash $HASHDIR/rn5/rn5_11nt.jf >> $LOGDIR/rn5_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48027 -k 23 -hash $HASHDIR/calJac3/calJac3_23nt.jf >> $LOGDIR/calJac3_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47027 -k 15 -hash $HASHDIR/calJac3/calJac3_15nt.jf >> $LOGDIR/calJac3_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46027 -k 11 -hash $HASHDIR/calJac3/calJac3_11nt.jf >> $LOGDIR/calJac3_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48036 -k 23 -hash $HASHDIR/susScr3/susScr3_23nt.jf >> $LOGDIR/susScr3_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47036 -k 15 -hash $HASHDIR/susScr3/susScr3_15nt.jf >> $LOGDIR/susScr3_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46036 -k 11 -hash $HASHDIR/susScr3/susScr3_11nt.jf >> $LOGDIR/susScr3_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48053 -k 23 -hash $HASHDIR/allMis1/allMis1_23nt.jf >> $LOGDIR/allMis1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47053 -k 15 -hash $HASHDIR/allMis1/allMis1_15nt.jf >> $LOGDIR/allMis1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46053 -k 11 -hash $HASHDIR/allMis1/allMis1_11nt.jf >> $LOGDIR/allMis1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48054 -k 23 -hash $HASHDIR/gadMor1/gadMor1_23nt.jf >> $LOGDIR/gadMor1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47054 -k 15 -hash $HASHDIR/gadMor1/gadMor1_15nt.jf >> $LOGDIR/gadMor1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46054 -k 11 -hash $HASHDIR/gadMor1/gadMor1_11nt.jf >> $LOGDIR/gadMor1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48055 -k 23 -hash $HASHDIR/melUnd1/melUnd1_23nt.jf >> $LOGDIR/melUnd1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47055 -k 15 -hash $HASHDIR/melUnd1/melUnd1_15nt.jf >> $LOGDIR/melUnd1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46055 -k 11 -hash $HASHDIR/melUnd1/melUnd1_11nt.jf >> $LOGDIR/melUnd1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48056 -k 23 -hash $HASHDIR/galGal4/galGal4_23nt.jf >> $LOGDIR/galGal4_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47056 -k 15 -hash $HASHDIR/galGal4/galGal4_15nt.jf >> $LOGDIR/galGal4_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46056 -k 11 -hash $HASHDIR/galGal4/galGal4_11nt.jf >> $LOGDIR/galGal4_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48057 -k 23 -hash $HASHDIR/latCha1/latCha1_23nt.jf >> $LOGDIR/latCha1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47057 -k 15 -hash $HASHDIR/latCha1/latCha1_15nt.jf >> $LOGDIR/latCha1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46057 -k 11 -hash $HASHDIR/latCha1/latCha1_11nt.jf >> $LOGDIR/latCha1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48058 -k 23 -hash $HASHDIR/calMil1/calMil1_23nt.jf >> $LOGDIR/calMil1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47058 -k 15 -hash $HASHDIR/calMil1/calMil1_15nt.jf >> $LOGDIR/calMil1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46058 -k 11 -hash $HASHDIR/calMil1/calMil1_11nt.jf >> $LOGDIR/calMil1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48059 -k 23 -hash $HASHDIR/fr3/fr3_23nt.jf >> $LOGDIR/fr3_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47059 -k 15 -hash $HASHDIR/fr3/fr3_15nt.jf >> $LOGDIR/fr3_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46059 -k 11 -hash $HASHDIR/fr3/fr3_11nt.jf >> $LOGDIR/fr3_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48060 -k 23 -hash $HASHDIR/petMar2/petMar2_23nt.jf >> $LOGDIR/petMar2_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47060 -k 15 -hash $HASHDIR/petMar2/petMar2_15nt.jf >> $LOGDIR/petMar2_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46060 -k 11 -hash $HASHDIR/petMar2/petMar2_11nt.jf >> $LOGDIR/petMar2_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48061 -k 23 -hash $HASHDIR/anoCar2/anoCar2_23nt.jf >> $LOGDIR/anoCar2_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47061 -k 15 -hash $HASHDIR/anoCar2/anoCar2_15nt.jf >> $LOGDIR/anoCar2_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46061 -k 11 -hash $HASHDIR/anoCar2/anoCar2_11nt.jf >> $LOGDIR/anoCar2_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48062 -k 23 -hash $HASHDIR/oryLat2/oryLat2_23nt.jf >> $LOGDIR/oryLat2_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47062 -k 15 -hash $HASHDIR/oryLat2/oryLat2_15nt.jf >> $LOGDIR/oryLat2_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46062 -k 11 -hash $HASHDIR/oryLat2/oryLat2_11nt.jf >> $LOGDIR/oryLat2_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48063 -k 23 -hash $HASHDIR/geoFor1/geoFor1_23nt.jf >> $LOGDIR/geoFor1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47063 -k 15 -hash $HASHDIR/geoFor1/geoFor1_15nt.jf >> $LOGDIR/geoFor1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46063 -k 11 -hash $HASHDIR/geoFor1/geoFor1_11nt.jf >> $LOGDIR/geoFor1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48064 -k 23 -hash $HASHDIR/oreNil2/oreNil2_23nt.jf >> $LOGDIR/oreNil2_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47064 -k 15 -hash $HASHDIR/oreNil2/oreNil2_15nt.jf >> $LOGDIR/oreNil2_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46064 -k 11 -hash $HASHDIR/oreNil2/oreNil2_11nt.jf >> $LOGDIR/oreNil2_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48065 -k 23 -hash $HASHDIR/chrPic1/chrPic1_23nt.jf >> $LOGDIR/chrPic1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47065 -k 15 -hash $HASHDIR/chrPic1/chrPic1_15nt.jf >> $LOGDIR/chrPic1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46065 -k 11 -hash $HASHDIR/chrPic1/chrPic1_11nt.jf >> $LOGDIR/chrPic1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48066 -k 23 -hash $HASHDIR/gasAcu1/gasAcu1_23nt.jf >> $LOGDIR/gasAcu1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47066 -k 15 -hash $HASHDIR/gasAcu1/gasAcu1_15nt.jf >> $LOGDIR/gasAcu1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46066 -k 11 -hash $HASHDIR/gasAcu1/gasAcu1_11nt.jf >> $LOGDIR/gasAcu1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48067 -k 23 -hash $HASHDIR/tetNig2/tetNig2_23nt.jf >> $LOGDIR/tetNig2_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47067 -k 15 -hash $HASHDIR/tetNig2/tetNig2_15nt.jf >> $LOGDIR/tetNig2_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46067 -k 11 -hash $HASHDIR/tetNig2/tetNig2_11nt.jf >> $LOGDIR/tetNig2_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48068 -k 23 -hash $HASHDIR/melGal1/melGal1_23nt.jf >> $LOGDIR/melGal1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47068 -k 15 -hash $HASHDIR/melGal1/melGal1_15nt.jf >> $LOGDIR/melGal1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46068 -k 11 -hash $HASHDIR/melGal1/melGal1_11nt.jf >> $LOGDIR/melGal1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48069 -k 23 -hash $HASHDIR/xenTro3/xenTro3_23nt.jf >> $LOGDIR/xenTro3_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47069 -k 15 -hash $HASHDIR/xenTro3/xenTro3_15nt.jf >> $LOGDIR/xenTro3_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46069 -k 11 -hash $HASHDIR/xenTro3/xenTro3_11nt.jf >> $LOGDIR/xenTro3_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48070 -k 23 -hash $HASHDIR/taeGut2/taeGut2_23nt.jf >> $LOGDIR/taeGut2_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47070 -k 15 -hash $HASHDIR/taeGut2/taeGut2_15nt.jf >> $LOGDIR/taeGut2_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46070 -k 11 -hash $HASHDIR/taeGut2/taeGut2_11nt.jf >> $LOGDIR/taeGut2_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48071 -k 23 -hash $HASHDIR/danRer7/danRer7_23nt.jf >> $LOGDIR/danRer7_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47071 -k 15 -hash $HASHDIR/danRer7/danRer7_15nt.jf >> $LOGDIR/danRer7_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46071 -k 11 -hash $HASHDIR/danRer7/danRer7_11nt.jf >> $LOGDIR/danRer7_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48072 -k 23 -hash $HASHDIR/ci2/ci2_23nt.jf >> $LOGDIR/ci2_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47072 -k 15 -hash $HASHDIR/ci2/ci2_15nt.jf >> $LOGDIR/ci2_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46072 -k 11 -hash $HASHDIR/ci2/ci2_11nt.jf >> $LOGDIR/ci2_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48073 -k 23 -hash $HASHDIR/braFlo1/braFlo1_23nt.jf >> $LOGDIR/braFlo1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47073 -k 15 -hash $HASHDIR/braFlo1/braFlo1_15nt.jf >> $LOGDIR/braFlo1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46073 -k 11 -hash $HASHDIR/braFlo1/braFlo1_11nt.jf >> $LOGDIR/braFlo1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48074 -k 23 -hash $HASHDIR/strPur2/strPur2_23nt.jf >> $LOGDIR/strPur2_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47074 -k 15 -hash $HASHDIR/strPur2/strPur2_15nt.jf >> $LOGDIR/strPur2_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46074 -k 11 -hash $HASHDIR/strPur2/strPur2_11nt.jf >> $LOGDIR/strPur2_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48075 -k 23 -hash $HASHDIR/anoGam1/anoGam1_23nt.jf >> $LOGDIR/anoGam1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47075 -k 15 -hash $HASHDIR/anoGam1/anoGam1_15nt.jf >> $LOGDIR/anoGam1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46075 -k 11 -hash $HASHDIR/anoGam1/anoGam1_11nt.jf >> $LOGDIR/anoGam1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48076 -k 23 -hash $HASHDIR/apiMel2/apiMel2_23nt.jf >> $LOGDIR/apiMel2_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47076 -k 15 -hash $HASHDIR/apiMel2/apiMel2_15nt.jf >> $LOGDIR/apiMel2_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46076 -k 11 -hash $HASHDIR/apiMel2/apiMel2_11nt.jf >> $LOGDIR/apiMel2_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48077 -k 23 -hash $HASHDIR/droAna2/droAna2_23nt.jf >> $LOGDIR/droAna2_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47077 -k 15 -hash $HASHDIR/droAna2/droAna2_15nt.jf >> $LOGDIR/droAna2_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46077 -k 11 -hash $HASHDIR/droAna2/droAna2_11nt.jf >> $LOGDIR/droAna2_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48078 -k 23 -hash $HASHDIR/droEre1/droEre1_23nt.jf >> $LOGDIR/droEre1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47078 -k 15 -hash $HASHDIR/droEre1/droEre1_15nt.jf >> $LOGDIR/droEre1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46078 -k 11 -hash $HASHDIR/droEre1/droEre1_11nt.jf >> $LOGDIR/droEre1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48079 -k 23 -hash $HASHDIR/droGri1/droGri1_23nt.jf >> $LOGDIR/droGri1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47079 -k 15 -hash $HASHDIR/droGri1/droGri1_15nt.jf >> $LOGDIR/droGri1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46079 -k 11 -hash $HASHDIR/droGri1/droGri1_11nt.jf >> $LOGDIR/droGri1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48080 -k 23 -hash $HASHDIR/dm6/dm6_23nt.jf >> $LOGDIR/dm6_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47080 -k 15 -hash $HASHDIR/dm6/dm6_15nt.jf >> $LOGDIR/dm6_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46080 -k 11 -hash $HASHDIR/dm6/dm6_11nt.jf >> $LOGDIR/dm6_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48081 -k 23 -hash $HASHDIR/dm3/dm3_23nt.jf >> $LOGDIR/dm3_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47081 -k 15 -hash $HASHDIR/dm3/dm3_15nt.jf >> $LOGDIR/dm3_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46081 -k 11 -hash $HASHDIR/dm3/dm3_11nt.jf >> $LOGDIR/dm3_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48082 -k 23 -hash $HASHDIR/droMoj2/droMoj2_23nt.jf >> $LOGDIR/droMoj2_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47082 -k 15 -hash $HASHDIR/droMoj2/droMoj2_15nt.jf >> $LOGDIR/droMoj2_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46082 -k 11 -hash $HASHDIR/droMoj2/droMoj2_11nt.jf >> $LOGDIR/droMoj2_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48083 -k 23 -hash $HASHDIR/droPer1/droPer1_23nt.jf >> $LOGDIR/droPer1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47083 -k 15 -hash $HASHDIR/droPer1/droPer1_15nt.jf >> $LOGDIR/droPer1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46083 -k 11 -hash $HASHDIR/droPer1/droPer1_11nt.jf >> $LOGDIR/droPer1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48084 -k 23 -hash $HASHDIR/dp3/dp3_23nt.jf >> $LOGDIR/dp3_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47084 -k 15 -hash $HASHDIR/dp3/dp3_15nt.jf >> $LOGDIR/dp3_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46084 -k 11 -hash $HASHDIR/dp3/dp3_11nt.jf >> $LOGDIR/dp3_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48085 -k 23 -hash $HASHDIR/droSec1/droSec1_23nt.jf >> $LOGDIR/droSec1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47085 -k 15 -hash $HASHDIR/droSec1/droSec1_15nt.jf >> $LOGDIR/droSec1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46085 -k 11 -hash $HASHDIR/droSec1/droSec1_11nt.jf >> $LOGDIR/droSec1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48086 -k 23 -hash $HASHDIR/droSim1/droSim1_23nt.jf >> $LOGDIR/droSim1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47086 -k 15 -hash $HASHDIR/droSim1/droSim1_15nt.jf >> $LOGDIR/droSim1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46086 -k 11 -hash $HASHDIR/droSim1/droSim1_11nt.jf >> $LOGDIR/droSim1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48087 -k 23 -hash $HASHDIR/droVir2/droVir2_23nt.jf >> $LOGDIR/droVir2_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47087 -k 15 -hash $HASHDIR/droVir2/droVir2_15nt.jf >> $LOGDIR/droVir2_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46087 -k 11 -hash $HASHDIR/droVir2/droVir2_11nt.jf >> $LOGDIR/droVir2_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48088 -k 23 -hash $HASHDIR/droYak2/droYak2_23nt.jf >> $LOGDIR/droYak2_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47088 -k 15 -hash $HASHDIR/droYak2/droYak2_15nt.jf >> $LOGDIR/droYak2_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46088 -k 11 -hash $HASHDIR/droYak2/droYak2_11nt.jf >> $LOGDIR/droYak2_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48089 -k 23 -hash $HASHDIR/caePb2/caePb2_23nt.jf >> $LOGDIR/caePb2_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47089 -k 15 -hash $HASHDIR/caePb2/caePb2_15nt.jf >> $LOGDIR/caePb2_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46089 -k 11 -hash $HASHDIR/caePb2/caePb2_11nt.jf >> $LOGDIR/caePb2_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48090 -k 23 -hash $HASHDIR/cb3/cb3_23nt.jf >> $LOGDIR/cb3_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47090 -k 15 -hash $HASHDIR/cb3/cb3_15nt.jf >> $LOGDIR/cb3_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46090 -k 11 -hash $HASHDIR/cb3/cb3_11nt.jf >> $LOGDIR/cb3_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48091 -k 23 -hash $HASHDIR/ce10/ce10_23nt.jf >> $LOGDIR/ce10_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47091 -k 15 -hash $HASHDIR/ce10/ce10_15nt.jf >> $LOGDIR/ce10_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46091 -k 11 -hash $HASHDIR/ce10/ce10_11nt.jf >> $LOGDIR/ce10_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48092 -k 23 -hash $HASHDIR/caeJap1/caeJap1_23nt.jf >> $LOGDIR/caeJap1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47092 -k 15 -hash $HASHDIR/caeJap1/caeJap1_15nt.jf >> $LOGDIR/caeJap1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46092 -k 11 -hash $HASHDIR/caeJap1/caeJap1_11nt.jf >> $LOGDIR/caeJap1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48093 -k 23 -hash $HASHDIR/caeRem3/caeRem3_23nt.jf >> $LOGDIR/caeRem3_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47093 -k 15 -hash $HASHDIR/caeRem3/caeRem3_15nt.jf >> $LOGDIR/caeRem3_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46093 -k 11 -hash $HASHDIR/caeRem3/caeRem3_11nt.jf >> $LOGDIR/caeRem3_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48094 -k 23 -hash $HASHDIR/priPac1/priPac1_23nt.jf >> $LOGDIR/priPac1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47094 -k 15 -hash $HASHDIR/priPac1/priPac1_15nt.jf >> $LOGDIR/priPac1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46094 -k 11 -hash $HASHDIR/priPac1/priPac1_11nt.jf >> $LOGDIR/priPac1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48095 -k 23 -hash $HASHDIR/sacCer3/sacCer3_23nt.jf >> $LOGDIR/sacCer3_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47095 -k 15 -hash $HASHDIR/sacCer3/sacCer3_15nt.jf >> $LOGDIR/sacCer3_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46095 -k 11 -hash $HASHDIR/sacCer3/sacCer3_11nt.jf >> $LOGDIR/sacCer3_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48096 -k 23 -hash $HASHDIR/aplCal1/aplCal1_23nt.jf >> $LOGDIR/aplCal1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47096 -k 15 -hash $HASHDIR/aplCal1/aplCal1_15nt.jf >> $LOGDIR/aplCal1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46096 -k 11 -hash $HASHDIR/aplCal1/aplCal1_11nt.jf >> $LOGDIR/aplCal1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48097 -k 23 -hash $HASHDIR/eboVir3/eboVir3_23nt.jf >> $LOGDIR/eboVir3_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47097 -k 15 -hash $HASHDIR/eboVir3/eboVir3_15nt.jf >> $LOGDIR/eboVir3_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46097 -k 11 -hash $HASHDIR/eboVir3/eboVir3_11nt.jf >> $LOGDIR/eboVir3_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48207 -k 23 -hash $HASHDIR/Xenla9/Xenla9_23nt.jf >> $LOGDIR/Xenla9_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47207 -k 15 -hash $HASHDIR/Xenla9/Xenla9_15nt.jf >> $LOGDIR/Xenla9_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46207 -k 11 -hash $HASHDIR/Xenla9/Xenla9_11nt.jf >> $LOGDIR/Xenla9_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48208 -k 23 -hash $HASHDIR/Xenla7/Xenla7_23nt.jf >> $LOGDIR/Xenla7_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47208 -k 15 -hash $HASHDIR/Xenla7/Xenla7_15nt.jf >> $LOGDIR/Xenla7_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46208 -k 11 -hash $HASHDIR/Xenla7/Xenla7_11nt.jf >> $LOGDIR/Xenla7_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48209 -k 23 -hash $HASHDIR/Xentr9/Xentr9_23nt.jf >> $LOGDIR/Xentr9_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47209 -k 15 -hash $HASHDIR/Xentr9/Xentr9_15nt.jf >> $LOGDIR/Xentr9_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46209 -k 11 -hash $HASHDIR/Xentr9/Xentr9_11nt.jf >> $LOGDIR/Xentr9_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48210 -k 23 -hash $HASHDIR/Xentr8/Xentr8_23nt.jf >> $LOGDIR/Xentr8_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47210 -k 15 -hash $HASHDIR/Xentr8/Xentr8_15nt.jf >> $LOGDIR/Xentr8_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46210 -k 11 -hash $HASHDIR/Xentr8/Xentr8_11nt.jf >> $LOGDIR/Xentr8_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48211 -k 23 -hash $HASHDIR/Xentr7/Xentr7_23nt.jf >> $LOGDIR/Xentr7_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47211 -k 15 -hash $HASHDIR/Xentr7/Xentr7_15nt.jf >> $LOGDIR/Xentr7_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46211 -k 11 -hash $HASHDIR/Xentr7/Xentr7_11nt.jf >> $LOGDIR/Xentr7_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48212 -k 23 -hash $HASHDIR/TAIR10/TAIR10_23nt.jf >> $LOGDIR/TAIR10_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47212 -k 15 -hash $HASHDIR/TAIR10/TAIR10_15nt.jf >> $LOGDIR/TAIR10_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46212 -k 11 -hash $HASHDIR/TAIR10/TAIR10_11nt.jf >> $LOGDIR/TAIR10_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48213 -k 23 -hash $HASHDIR/rice/rice_23nt.jf >> $LOGDIR/rice_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47213 -k 15 -hash $HASHDIR/rice/rice_15nt.jf >> $LOGDIR/rice_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46213 -k 11 -hash $HASHDIR/rice/rice_11nt.jf >> $LOGDIR/rice_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48214 -k 23 -hash $HASHDIR/sorBic/sorBic_23nt.jf >> $LOGDIR/sorBic_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47214 -k 15 -hash $HASHDIR/sorBic/sorBic_15nt.jf >> $LOGDIR/sorBic_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46214 -k 11 -hash $HASHDIR/sorBic/sorBic_11nt.jf >> $LOGDIR/sorBic_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48215 -k 23 -hash $HASHDIR/Brana_v4.1/Brana_v4.1_23nt.jf >> $LOGDIR/Brana_v4.1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47215 -k 15 -hash $HASHDIR/Brana_v4.1/Brana_v4.1_15nt.jf >> $LOGDIR/Brana_v4.1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46215 -k 11 -hash $HASHDIR/Brana_v4.1/Brana_v4.1_11nt.jf >> $LOGDIR/Brana_v4.1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48216 -k 23 -hash $HASHDIR/lotus_r3.0/lotus_r3.0_23nt.jf >> $LOGDIR/lotus_r3.0_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47216 -k 15 -hash $HASHDIR/lotus_r3.0/lotus_r3.0_15nt.jf >> $LOGDIR/lotus_r3.0_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46216 -k 11 -hash $HASHDIR/lotus_r3.0/lotus_r3.0_11nt.jf >> $LOGDIR/lotus_r3.0_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48217 -k 23 -hash $HASHDIR/Niben_v1.0.1/Niben_v1.0.1_23nt.jf >> $LOGDIR/Niben_v1.0.1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47217 -k 15 -hash $HASHDIR/Niben_v1.0.1/Niben_v1.0.1_15nt.jf >> $LOGDIR/Niben_v1.0.1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46217 -k 11 -hash $HASHDIR/Niben_v1.0.1/Niben_v1.0.1_11nt.jf >> $LOGDIR/Niben_v1.0.1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48218 -k 23 -hash $HASHDIR/adzuki_ver3/adzuki_ver3_23nt.jf >> $LOGDIR/adzuki_ver3_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47218 -k 15 -hash $HASHDIR/adzuki_ver3/adzuki_ver3_15nt.jf >> $LOGDIR/adzuki_ver3_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46218 -k 11 -hash $HASHDIR/adzuki_ver3/adzuki_ver3_11nt.jf >> $LOGDIR/adzuki_ver3_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48219 -k 23 -hash $HASHDIR/RSA_r1.0/RSA_r1.0_23nt.jf >> $LOGDIR/RSA_r1.0_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47219 -k 15 -hash $HASHDIR/RSA_r1.0/RSA_r1.0_15nt.jf >> $LOGDIR/RSA_r1.0_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46219 -k 11 -hash $HASHDIR/RSA_r1.0/RSA_r1.0_11nt.jf >> $LOGDIR/RSA_r1.0_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48220 -k 23 -hash $HASHDIR/Ptrichocarpa_v3.0/Ptrichocarpa_v3.0_23nt.jf >> $LOGDIR/Ptrichocarpa_v3.0_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47220 -k 15 -hash $HASHDIR/Ptrichocarpa_v3.0/Ptrichocarpa_v3.0_15nt.jf >> $LOGDIR/Ptrichocarpa_v3.0_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46220 -k 11 -hash $HASHDIR/Ptrichocarpa_v3.0/Ptrichocarpa_v3.0_11nt.jf >> $LOGDIR/Ptrichocarpa_v3.0_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48221 -k 23 -hash $HASHDIR/bmor1/bmor1_23nt.jf >> $LOGDIR/bmor1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47221 -k 15 -hash $HASHDIR/bmor1/bmor1_15nt.jf >> $LOGDIR/bmor1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46221 -k 11 -hash $HASHDIR/bmor1/bmor1_11nt.jf >> $LOGDIR/bmor1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48222 -k 23 -hash $HASHDIR/pombe/pombe_23nt.jf >> $LOGDIR/pombe_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47222 -k 15 -hash $HASHDIR/pombe/pombe_15nt.jf >> $LOGDIR/pombe_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46222 -k 11 -hash $HASHDIR/pombe/pombe_11nt.jf >> $LOGDIR/pombe_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48228 -k 23 -hash $HASHDIR/MG8/MG8_23nt.jf >> $LOGDIR/MG8_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47228 -k 15 -hash $HASHDIR/MG8/MG8_15nt.jf >> $LOGDIR/MG8_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46228 -k 11 -hash $HASHDIR/MG8/MG8_11nt.jf >> $LOGDIR/MG8_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48223 -k 23 -hash $HASHDIR/macaque_CE_1/macaque_CE_1_23nt.jf >> $LOGDIR/macaque_CE_1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47223 -k 15 -hash $HASHDIR/macaque_CE_1/macaque_CE_1_15nt.jf >> $LOGDIR/macaque_CE_1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46223 -k 11 -hash $HASHDIR/macaque_CE_1/macaque_CE_1_11nt.jf >> $LOGDIR/macaque_CE_1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48224 -k 23 -hash $HASHDIR/KH/KH_23nt.jf >> $LOGDIR/KH_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47224 -k 15 -hash $HASHDIR/KH/KH_15nt.jf >> $LOGDIR/KH_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46224 -k 11 -hash $HASHDIR/KH/KH_11nt.jf >> $LOGDIR/KH_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48225 -k 23 -hash $HASHDIR/Spur_v3.1/Spur_v3.1_23nt.jf >> $LOGDIR/Spur_v3.1_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47225 -k 15 -hash $HASHDIR/Spur_v3.1/Spur_v3.1_15nt.jf >> $LOGDIR/Spur_v3.1_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46225 -k 11 -hash $HASHDIR/Spur_v3.1/Spur_v3.1_11nt.jf >> $LOGDIR/Spur_v3.1_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48226 -k 23 -hash $HASHDIR/h7/h7_23nt.jf >> $LOGDIR/h7_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47226 -k 15 -hash $HASHDIR/h7/h7_15nt.jf >> $LOGDIR/h7_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46226 -k 11 -hash $HASHDIR/h7/h7_11nt.jf >> $LOGDIR/h7_11nt.log 2>&1 &

	sudo -u nobody $JELFISH -p 48227 -k 23 -hash $HASHDIR/Hydra_RP_1.0/Hydra_RP_1.0_23nt.jf >> $LOGDIR/Hydra_RP_1.0_23nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 47227 -k 15 -hash $HASHDIR/Hydra_RP_1.0/Hydra_RP_1.0_15nt.jf >> $LOGDIR/Hydra_RP_1.0_15nt.log 2>&1 &
	sudo -u nobody $JELFISH -p 46227 -k 11 -hash $HASHDIR/Hydra_RP_1.0/Hydra_RP_1.0_11nt.jf >> $LOGDIR/Hydra_RP_1.0_11nt.log 2>&1 &
}

StopService ()
{
	ConsoleMessage "Stopping CRISPRdirect jellyfish server"
	kill $(ps -U nobody | sed 's/^\ *//' | grep jellyfishd | cut -d ' ' -f 1)
}

RestartService ()
{
	StopService
	StartService
}

if test -x $JELFISH ; then
	RunService "$1"
else
	ConsoleMessage "Could not find CRISPRdirect jellyfish server script!"
fi
